[package]
name = "update-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.15"
aws-sdk-dynamodb = "1.63.0"
flate2 = "1.0"
tokio = { version = "1", features = ["full", "macros"] }
